<?php
ini_set("memory_limit","2048M");
set_time_limit(0);
require_once "../lib/mpdf57/mpdf.php";

$pdf = new MPDF();

$pdf->Open("", "A4");

$pdf->AddPage("L");

$pdf->SetFont("Arial","N",10);

$pdf->WriteHTML("
	<style>
		.table{
			border-collapse: collapse;
		}
	</style>".str_replace('<span class="fa fa-check"></span>', "<img src='../images/check_btn.png' />", $_POST['data']));
$pdf->setHTMLFooter("<div style='font-size:7px; font-family:arial; font-weight:bold; text-align:right; border-top:1px dashed #dfdfdf; color:#dfdfdf;'><div style='float:left; color:#000; text-align:left; border:0px solid red; width:49%;'>Generated by: {$documentGenerator}</div><div style='float:right; border:0px solid red; width:49%;'>printed using care software | easy one ltd</div></div>");
$filename = "./register.pdf";

// echo str_replace('<span class="fa fa-check"></span>', "<img src='../images/check_btn.png' />", $_POST['data']);
//echo $filename;
$pdf->Output($filename); 
?>
<a href="<?= $filename ?>" target="_blank" id="downladNow">File Reay</a>
<script type="text/javascript">
	setTimeout(function(e){
		$("#downladNow")[0].click();
	}, 1000);
</script>